#!/bin/bash

###
### bitcoin core linux autocompiler
### run with "sudo"
###

set -x
set -e


# Usage: $0 <https://bitcoincore.org/bin/bitcoin-core-...>
if [ "$#" != "1" ]; then
    echo "Usage: sudo $0 <https://bitcoincore.org/bin/bitcoin-core-...>"
    exit 1
else
    echo "OK..." $1    
fi

DIRBITCOINCORE="https://bitcoincore.org/bin/"
wget $DIRBITCOINCORE -O index
BITCOINCORELAST=$(grep -o 'bitcoin-core-.*' index | tail -n 1 | awk -F "\/" '{printf ($1)}' )'{printf ($1)}'
FILE=$(echo BITCOINCORELAST | sed 's/core-//')

#FILE=$(echo $1 | awk -F "\/" '{printf tolower($6)}')
#DIRHTTP=$(echo $1 | awk -F "\/" '{printf tolower($1"/"$2"/"$3"/"$4"/"$5"/")}')
#FILE=$(echo $1 | awk -F "\/" '{printf tolower($5".tar.gz")}' | sed 's/core-//')
DIRBTC=$(echo $FILE | awk -F ".tar" '{printf tolower($1)}')

echo 
echo $DIRBITCOINCORE$BITCOINCORELAST$FILE
echo 
wget $DIRBITCOINCORE$BITCOINCORELAST$FILE -O $FILE
wget $DIRBITCOINCORE$BITCOINCORELAST"SHA256SUMS"
wget $DIRBITCOINCORE$BITCOINCORELAST"SHA256SUMS.asc"

CHECKSUM=$(sha256sum --ignore-missing --check SHA256SUMS)
if [ $? -eq 0 ]; then	
	echo "OK..."
	echo $(sha256sum --ignore-missing --check SHA256SUMS | awk -F ":" '{printf tolower($2)}')	
else
	echo "KO..."
	echo $(sha256sum --ignore-missing --check SHA256SUMS | awk -F ":" '{printf tolower($2)}')
	exit $?
fi
tar -xvf $FILE
cd $DIRBTC
pwd

sudo apt -y install build-essential libtool autotools-dev automake pkg-config bsdmainutils python3
sudo apt -y install libevent-dev libboost-dev
sudo apt -y install libsqlite3-dev

./contrib/install_db4.sh `pwd`

sudo apt -y install libminiupnpc-dev libnatpmp-dev
sudo apt -y install libzmq3-dev
sudo apt -y install systemtap-sdt-dev

sudo apt -y install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools
sudo apt -y install qtwayland5
sudo apt -y install libqrencode-dev

./autogen.sh
export BDB_PREFIX=$(pwd)'/db4'
./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include"
make -j "$(($(nproc)+1))"
sudo make install

echo "well done, enjoy!"

